### PR TITLE
(PE-34072) Change scheduled jobs URL used by OrchestratorDispatcher to new SJM path

### PR DESCRIPTION
**Pull request by rileynewton**
WIP.

### CODE REVIEW

**Comment by donoghuc** [comment]
I'm not following why you need to update these for your console work?

**Comment by rileynewton** [comment]
> I'm not following why you need to update these for your console work?

Maybe we don't actually need the tests that are there but currently `OrchestratorDispatcher` is used in pe-console-ui acceptance tests such as https://github.com/puppetlabs/pe-console-ui/blob/main/acceptance/tests/nm/ui/access_control/jobs_and_tasks/delete-scheduled-tasks.rb, there's a whole bunch of helpers involving it in https://github.com/puppetlabs/pe-console-ui/blob/main/acceptance/helpers/beaker/orchestrator_helpers.rb so I just quickly included it.

**Review by mwaggett — APPROVED** [review]

**Comment by donoghuc** [comment]
I'm not convinced this is the right thing to do. IN orchestrator we are already hitting the correct endpoints. I think that pe_acceptance_tests are using these helpers. The endpoints AND the expected payloads need to change. So if we release this any consumer that is using the existing helpers (at least for POST endpoints) will start to fail.

**Comment by donoghuc** [comment]
I did a quick look through the console acceptance tests and was not seeing where these helpers are used (which I why I asked why this PR was opened in the first place because I assumed it was to unblock PE-34072)

**Comment by rileynewton** [comment]
I'm not sure this is the right thing to do either but take a look again at https://github.com/puppetlabs/pe-console-ui/blob/main/acceptance/tests/nm/ui/access_control/jobs_and_tasks/delete-scheduled-tasks.rb -- basically all the functions mentioning scheduling use OrchestratorDispatcher, so I was thinking this needs to be changed for the acceptance tests to pass.

**Comment by rileynewton** [comment]
Closing in favor of developing new helpers in pe-console-ui rather than doing scooter modification.

**Pull request closed without merging**
